export const FETCH_USER = "FETCH_USER";
export const FETCH_DATASETS = "FETCH_DATASETS";
export const FETCH_DEMO_DATASETS = "FETCH_DEMO_DATASETS";

export const SET_SELECTION_TIME = "SET_SELECTION_TIME";

export const SET_CURRENT_DATASET = "SET_CURRENT_DATASET";
export const SET_CURRENT_TYPES_JSON = "SET_CURRENT_TYPES_JSON";
export const SET_CURRENT_UMIS_JSON = "SET_CURRENT_UMIS_JSON";
export const SET_WAITING_FOR_DATA = "SET_WAITING_FOR_DATA";

export const SET_FULLSCREEN = "SET_FULLSCREEN";

export const SET_COLORMAP = "SET_COLORMAP";
export const SET_POINTSIZE = "SET_POINTSIZE";

export const SET_SELECT_TYPE = "SET_SELECT_TYPE";
export const SET_SELECT_UMI_IDX = "SET_SELECT_UMI";

export const RESET_APP = "RESET_APP";
export const SET_APP_MODAL = "SET_APP_MODAL";

export const SET_MOUSE_XY = "SET_MOUSE_XY";
export const SET_VIEWPORT_WH ="SET_VIEWPORT_WH";
export const SET_VIEWPORT_TRANSFORM ="SET_VIEWPORT_TRANSFORM";
export const SET_VIEWPORT_XY = "SET_VIEWPORT_XY";

export const SET_QUERY_UMI_SUBSTRING="SET_QUERY_UMI_SUBSTRING";
export const SET_QUERY_UMI_TYPE="SET_QUERY_UMI_TYPE";

export const COMPONENTS_REGISTER_IMAGE_CONTAINER="COMPONENTS_REGISTER_IMAGE_CONTAINER";

export const CLEAN_RESET_WITH_JSON = "CLEAN_RESET_WITH_JSON";
export const UPDATE_STATE_WITH_JSON = "UPDATE_STATE_WITH_JSON";
export const RESET = "RESET";
export const RESET_UI_ONLY = "RESET_UI_ONLY";
